
package introsde.healthmanagement.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://soap.healthmanagement.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @return
     *     returns java.util.List<introsde.healthmanagement.soap.Person>
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonListResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/readPersonListRequest", output = "http://soap.healthmanagement.introsde/People/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param measureType
     * @param personId
     * @param mid
     * @return
     *     returns introsde.healthmanagement.soap.Measure
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "http://soap.healthmanagement.introsde/")
    @RequestWrapper(localName = "readPersonMeasurement", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonMeasurement")
    @ResponseWrapper(localName = "readPersonMeasurementResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonMeasurementResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/readPersonMeasurementRequest", output = "http://soap.healthmanagement.introsde/People/readPersonMeasurementResponse")
    public Measure readPersonMeasurement(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "mid", targetNamespace = "")
        Long mid);

    /**
     * 
     * @param measure
     * @param personId
     */
    @WebMethod
    @RequestWrapper(localName = "savePersonMeasurement", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.SavePersonMeasurement")
    @ResponseWrapper(localName = "savePersonMeasurementResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.SavePersonMeasurementResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/savePersonMeasurementRequest", output = "http://soap.healthmanagement.introsde/People/savePersonMeasurementResponse")
    public void savePersonMeasurement(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measure", targetNamespace = "http://soap.healthmanagement.introsde/", mode = WebParam.Mode.INOUT)
        Holder<Measure> measure);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "measureType", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureTypes", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadMeasureTypes")
    @ResponseWrapper(localName = "readMeasureTypesResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadMeasureTypesResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/readMeasureTypesRequest", output = "http://soap.healthmanagement.introsde/People/readMeasureTypesResponse")
    public List<String> readMeasureTypes();

    /**
     * 
     * @param measure
     * @param personId
     */
    @WebMethod
    @RequestWrapper(localName = "updatePersonMeasure", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.UpdatePersonMeasure")
    @ResponseWrapper(localName = "updatePersonMeasureResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.UpdatePersonMeasureResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/updatePersonMeasureRequest", output = "http://soap.healthmanagement.introsde/People/updatePersonMeasureResponse")
    public void updatePersonMeasure(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measure", targetNamespace = "http://soap.healthmanagement.introsde/", mode = WebParam.Mode.INOUT)
        Holder<Measure> measure);

    /**
     * 
     * @param measureType
     * @param personId
     * @return
     *     returns java.util.List<introsde.healthmanagement.soap.Measure>
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "http://soap.healthmanagement.introsde/")
    @RequestWrapper(localName = "readPersonHistory", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonHistory")
    @ResponseWrapper(localName = "readPersonHistoryResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonHistoryResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/readPersonHistoryRequest", output = "http://soap.healthmanagement.introsde/People/readPersonHistoryResponse")
    public List<Measure> readPersonHistory(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @param after
     * @param before
     * @param measureType
     * @param personId
     * @return
     *     returns java.util.List<introsde.healthmanagement.soap.Measure>
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "http://soap.healthmanagement.introsde/")
    @RequestWrapper(localName = "readPersonMeasureByDates", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonMeasureByDates")
    @ResponseWrapper(localName = "readPersonMeasureByDatesResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonMeasureByDatesResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/readPersonMeasureByDatesRequest", output = "http://soap.healthmanagement.introsde/People/readPersonMeasureByDatesResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://soap.healthmanagement.introsde/People/readPersonMeasureByDates/Fault/ParseException")
    })
    public List<Measure> readPersonMeasureByDates(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "before", targetNamespace = "")
        XMLGregorianCalendar before,
        @WebParam(name = "after", targetNamespace = "")
        XMLGregorianCalendar after)
        throws ParseException_Exception
    ;

    /**
     * 
     * @param personId
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.DeletePersonResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/deletePersonRequest", output = "http://soap.healthmanagement.introsde/People/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "personId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Long> personId);

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.healthmanagement.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/readPersonRequest", output = "http://soap.healthmanagement.introsde/People/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        Long personId);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.UpdatePersonResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/updatePersonRequest", output = "http://soap.healthmanagement.introsde/People/updatePersonResponse")
    public void updatePerson(
        @WebParam(name = "person", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Person> person);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.CreatePersonResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/createPersonRequest", output = "http://soap.healthmanagement.introsde/People/createPersonResponse")
    public void createPerson(
        @WebParam(name = "person", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Person> person);

    /**
     * 
     * @param minValue
     * @param measureType
     * @param maxValue
     * @return
     *     returns java.util.List<introsde.healthmanagement.soap.Person>
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPersonListByMeasurement", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonListByMeasurement")
    @ResponseWrapper(localName = "readPersonListByMeasurementResponse", targetNamespace = "http://soap.healthmanagement.introsde/", className = "introsde.healthmanagement.soap.ReadPersonListByMeasurementResponse")
    @Action(input = "http://soap.healthmanagement.introsde/People/readPersonListByMeasurementRequest", output = "http://soap.healthmanagement.introsde/People/readPersonListByMeasurementResponse")
    public List<Person> readPersonListByMeasurement(
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "maxValue", targetNamespace = "")
        String maxValue,
        @WebParam(name = "minValue", targetNamespace = "")
        String minValue);

}
